version: '3.8'

services:
  # Service Java Spring Boot
  backend:
    build:
      context: ./gestion-stock-backend
    ports:
      - "9091:9091"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/gestion_stock?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_APPLICATION_NAME=gestion-stock-backend
    depends_on:
      - db
    networks:
      - backend_network
    restart: always

  # Service Angular
  frontend:
    build:
      context: ./front-stock-management
    ports:
      - "4200:4200"
    networks:
      - backend_network
    restart: always

  # Service MySQL
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: gestion_stock
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - backend_network
    restart: always

  # Service React
  react-frontend:
    build:
      context: ./product-management-frontend
    ports:
      - "80:80"
    networks:
      - backend_network
    restart: always

  # Service Node.js
  nodejs-backend:
    build:
      context: ./product-management-backend
    ports:
      - "5000:5000"
    networks:
      - backend_network
    depends_on:
      - backend
    restart: always

  # Service phpMyAdmin
  phpmyadmin:
    image: phpmyadmin
    environment:
      PMA_HOST: db
    ports:
      - "8081:80"
    networks:
      - backend_network
    restart: always

  # Service PostgreSQL pour Kong (remplacé par l'image officielle PostgreSQL)
  kong-database:
    image: postgres:13 # Utilisation de l'image officielle PostgreSQL
    container_name: kong-database
    environment:
      - POSTGRES_USER=kong
      - POSTGRES_DB=kong
      - POSTGRES_PASSWORD=kong
    ports:
      - "5432:5432"
    restart: always
    networks:
      - backend_network

  # Service Kong (API Gateway)
  kong:
    image: kong:latest
    container_name: kong
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=kong-database
      - KONG_PG_PASSWORD=kong
      - KONG_PROXY_ACCESS_LOG=/dev/stdout
      - KONG_PROXY_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_ACCESS_LOG=/dev/stdout
      - KONG_ADMIN_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_LISTEN=0.0.0.0:8001
    ports:
      - "8000:8000"   # Port HTTP pour accéder au gateway
      - "8443:8443"   # Port HTTPS pour accéder au gateway
    depends_on:
      - kong-database
    networks:
      - backend_network
    restart: always

volumes:
  mysql-data:  # Volume pour persister les données MySQL

networks:
  backend_network:
    driver: bridge
