version: '3.8'

services:
  # Service Java Spring Boot
  backend:
    build:
      context: ./product-management-backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/gestion_stock?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_APPLICATION_NAME=gestion-stock-backend
    depends_on:
      - db
    networks:
      - backend_network
    restart: always

  # Service Angular
  frontend:
    build:
      context: ./front-stock-management
    ports:
      - "4200:4200"
    networks:
      - backend_network
    restart: always

  # Service React
  react-frontend:
    build:
      context: ./product-management-frontend
    ports:
      - "3000:3000"
    networks:
      - backend_network
    restart: always

  # Service Node.js
  nodejs-backend:
    build:
      context: ./gestion-stock-backend
    ports:
      - "5000:5000"
    networks:
      - backend_network
    restart: always

  # Service MySQL
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: gestion_stock
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - backend_network
    restart: always

  # Service phpMyAdmin
  phpmyadmin:
    image: phpmyadmin
    environment:
      PMA_HOST: db
    ports:
      - "8081:80"
    networks:
      - backend_network
    restart: always

volumes:
  mysql-data:

networks:
  backend_network:
    driver: bridge
