version: '3.8'

services:
  backend:
    build:
      context: ./gestion-stock-backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/gestion_stock
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    depends_on:
      - db
    networks:
      - backend_network
    restart: always

  frontend:
    build:
      context: ./front-stock-management
    ports:
      - "80:80"
    networks:
      - backend_network
    restart: always

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: gestion_stock
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - backend_network
    restart: always

volumes:
  mysql-data:

networks:
  backend_network:
    driver: bridge
