version: '3.8'

services:
  backend:
    build:
      context: ./gestion-stock-backend
    ports:
      - "8080:8080"  # Expose le port 8080 du backend pour l'accès
    environment:
      # Variables d'environnement pour la connexion à la base de données
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/gestion_stock?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_APPLICATION_NAME=gestion-stock-backend
    depends_on:
      - db
    networks:
      - backend_network
    restart: always

  frontend:
    build:
      context: ./front-stock-management
    ports:
      - "4200:4200"  # Assure-toi que le frontend est accessible via le port 4200
    networks:
      - backend_network
    restart: always

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: gestion_stock
    ports:
      - "3306:3306"  # Expose le port 3306 pour accéder à la base de données en externe
    volumes:
      - mysql-data:/var/lib/mysql  # Persiste les données dans un volume
    networks:
      - backend_network
    restart: always

volumes:
  mysql-data:  # Le volume pour la persistance des données MySQL

networks:
  backend_network:
    driver: bridge  # Crée un réseau pour permettre la communication entre les conteneurs
